### ISSUE TITLE
Require a real version of httpful

### ISSUE THREAD

**Issue by Incognito** [urbanairship/php-library2#27]
https://github.com/urbanairship/php-library2/blob/master/composer.json#L26

This is considered harmful, I'd be very happy if there was a known version we can use as httpful is also in the v0 range, so they can break their API at any time according to semver.

Thanks! :smile:

**Comment by pdxmele** [comment]
We'll take a look at this. Thanks!

**Comment by pdxmele** [comment]
We just released a new version that fixes this. Docs aren't up just yet (we need to fix our docs deployment), but it should be available.
