### ISSUE TITLE
No support for in_app in push notification

### ISSUE THREAD

**Issue by phpmypython** [urbanairship/php-library2#28]
When setting up a push notification there is no way to pass in the info for a in_app notification referenced in the API here.
http://docs.urbanairship.com/api/ua.html#api-in-app-display-object

**Comment by pdxmele** [comment]
Thanks for the enhancement request! We'll do our best to get this in with our next release.

**Comment by pdxmele** [comment]
We just released a new version that fixes this. Docs aren't up just yet (we need to fix our docs deployment), but it should be available now!
