### ISSUE TITLE
How specify named user in Audience for Push notification?

### ISSUE THREAD

**Issue by keepitsimple** [urbanairship/php-library2#29]
I checked the documentation and the PHP library code. API v3 supports named user, but PHP library doesn't allow to use it.

**Comment by jonbest** [comment]
i created a pull request https://github.com/urbanairship/php-library2/pull/26 that will implement named user support

**Comment by strusewych** [comment]
@devinsmythe you indicated on pull request #26 that there would be a new release out soon that will include named users, could you please provide some clarity as to the expected timeline?

**Comment by keepitsimple** [comment]
It's fixed now. Thank you!
