### ISSUE TITLE
Send push to multiple device types

### ISSUE THREAD

**Issue by vaibhavmalushte** [urbanairship/php-library2#30]
Hi,
We want to send push messages to our subscribers and we have captured their device tokens and device types. Now on certain events we want to send them a push message. Do I need to pass seprate array of each device type to push method or I can send all device tokens at a time and library will take care of genrating playload as per device type?
Please advice.

Thank you,
Vaibhav

**Comment by pdxmele** [comment]
Hi @vaibhavmalushte , please reach out to our support team via https://support.urbanairship.com / support@urbanairship.com, they can walk you through it and their platform will be better for back and forth troubleshooting than Github. Thanks!
