### ISSUE TITLE
Send Custom Key from PHP Code

### ISSUE THREAD

**Issue by darkholiday** [urbanairship/php-library2#32]
I would like to send a custom key like the one offered in the website.

**Comment by pdxmele** [comment]
Thanks for the enhancement request! We'll do our best to get this in with our next release.

**Comment by pdxmele** [comment]
Thanks for the enhancement request! We'll do our best to get this in with our next release.

**Comment by pdxmele** [comment]
Actually, we do allow this now, under "extra" -- please see https://github.com/urbanairship/php-library2/blob/master/src/UrbanAirship/Push/Notification.php#L42 etc
