### ISSUE TITLE
web console API version is different from SDK's

### ISSUE THREAD

**Issue by hackintos** [urbanairship/php-library2#34]
Hi UrbanAirship,

I noticed that the API version used via Web console dashboard (i.e. Version 2) is different from SDK's (i.e. Version 3). Is there a reason web console is behind SDK's?
![developer_tools_-_https___go_urbanairship_com_apps_edo_f8ihrms_ahwq5dw5aa_messages_overview__and_punterswebteam___punters_com_au___pull_requests_ _bitbucket](https://user-images.githubusercontent.com/1762174/39403870-7a2ba466-4bc9-11e8-8ffd-7f44c0e2d4d5.png)
![punters_com_au____dev_punters_com_au__-_____vendor_urbanairship_urbanairship_src_urbanairship_airship_php](https://user-images.githubusercontent.com/1762174/39403877-9393df40-4bc9-11e8-98e3-7fba82f97872.png)

**Comment by pdxmele** [comment]
The API used on the website is an internal API with a different versioning system, completely separate from our public API endpoints. If you have further questions, please contact our support team at https://support.urbanairship.com
