### ISSUE TITLE
Support for Monolog 2.*

### ISSUE THREAD

**Issue by mangrovestudios** [urbanairship/php-library2#35]
Developing an app using PHP framework Laravel version 8 which has a requirement of Monolog 2.

There is currently a conflict together with this library as it requires Monolog 1.*.

**Comment by nidhishPfizer** [comment]
Hello Urbanairship Team,

Could the required monolog version be upgraded to 2.x

**Comment by pdxmele** [comment]
Hi, sorry about the delay. We'll try to look at this soon.

**Comment by Jahdeh** [comment]
Hi @mangrovestudios and @nidhishPfizer, this has been updated to allow monolog versions greater than one. Thanks for letting us know!

**Comment by nidhishPfizer** [comment]
Thanks @Jahdeh  for the fix
